### ISSUE TITLE
Voortgang week 1 

### ISSUE THREAD

**Issue by TM11153431** [MirjaLagerwaard/ProgrammeerprojectData#1]
Hoi Mirja

Klinkt als een interessant project! Maar let wel op dat je het logboek (PROCESS.md) goed bijhoudt, zodat je dit aan het einde van het project niet allemaal nog terug moet halen wat je ook al weer iedere dag hebt gedaan. Daarnaast zie ik in je schets maar 2 visualisaties. Ik lees in je verhaal wel dat het er meer zijn, maar zorg dat je echt een schets maakt van je MVP, waarin de drie gelinkte visualisaties en de twee interactieve elementen te zien zijn.

**Comment by MirjaLagerwaard** [comment]
Bedankt voor de feedback!

* Logboek was ik inderdaad gisteren mee begonnen, alleen had ik nog niet gepusht 
* Ik heb een schets van de 3 visualisaties staan bij mijn design document, maar ik zal de afbeelding van de readme even aanpassen.
